apiVersion: 1

datasources:
  - name: InfluxDB_k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    password: ''
    user: ''
    database: k6
    basicAuth: false
    isDefault: true
    editable: true
