{
 "title": "k6 Load Testing Results",
 "tags": [ "k6" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testid",
    "label": "Test ID",
    "query": "show tag values from \"http_reqs\" with key = \"testid\""
   }
  ]
 },
 "panels": [
  { "title": "Test Information", "type": "row", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 2 },
   "options": {
    "content": "This dashboard is a slightly modified version of the one available on [Grafana.com](https://grafana.com/grafana/dashboards/2587).\n\nIt is set up to be easily used with the k6 docker-compose setup, and has a **testid** variable added that can be used to filter by a specific test run. The **testid** needs to be passed as a tag from your k6 script: `k6 run --tag testid=your-unique-id script.js`\n\nFor more information on k6, see [k6.io](https://k6.io)."
   }
  },
  {
   "title": "Virtual Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "query": "SELECT last(\"value\") FROM \"vus\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Requests per second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "$tag_group - $tag_method",
     "groupBy": [
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "testid", "operator": "=", "value": "$testid" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "http_reqs",
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "testid", "operator": "=", "value": "$testid" }
     ]
    }
   ]
  },
  { "title": "Durations", "type": "row", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "$tag_group - $tag_method",
     "groupBy": [
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "testid", "operator": "=", "value": "$testid" }
     ]
    }
   ]
  },
  {
   "title": "Avg. duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "http_req_duration",
     "query": "SELECT mean(\"value\") FROM \"http_req_duration\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "testid", "operator": "=", "value": "$testid" }
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "$tag_group - $tag_method",
     "groupBy": [
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "http_req_failed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "testid", "operator": "=", "value": "$testid" }
     ]
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "http_req_failed",
     "query": "SELECT count(\"value\") FROM \"http_req_failed\" WHERE $timeFilter AND value = 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "testid", "operator": "=", "value": "$testid" }
     ]
    }
   ]
  }
 ]
}